### ISSUE TITLE
Unable to parse IPv6 nameserver with scope identifier

### ISSUE THREAD

**Issue by Frans-Willem** [tailhook/resolv-conf#1]
My resolv.conf looks like this:

```
# Generated by resolvconf
search local
nameserver 192.168.1.1
nameserver fe80::c66e:1fff:feea:c02a%bridge0
```

and this library refuses to parse the last nameserver, even though the rest of the system uses it fine.

**Comment by tailhook** [comment]
Hm, I didn't know this is possible. Is this linux box?

This probably requires changing the library interface. I.e. the address with a scope identifier doesn't fit `IpAddr` structure, right?

Anyway, would you like to make a pull request?
