### ISSUE TITLE
Release of 0.5.0

### ISSUE THREAD

**Issue by tailhook** [tailhook/resolv-conf#3]
What's left to be done/discussed:

1. [ ] Hide internal structure of Config or make it extensible (for forward compatibility)
2. [ ] May be make all fields `Option<xxx>` so it's clean which are explicitly set
3. [ ] Use `failure` crate instead of quick-error
4. [x] `warn(missing_docs)`
5. [x] `warn(missing_debug_implementations)`
6. [x] Minimal example code in `lib.rs`

**Comment by tailhook** [comment]
It looks like we [decided](#2) to postpone [2] (making  fields optional) and [3] (`failure` crate). Still not sure about the first one.

**Comment by little-dude** [comment]
I can fix the `warn(missing_docs)` and `warn(missing_debug_implementations)`, as well as add a minimal code example in `lib.rs` in a PR in the next few days.

For the first item, are you thinking of keeping the exact same struct, but make the fields private and provide public `get_` and `set_` methods for each field? If so that's also something I can do (in a separate PR probably).

**Comment by tailhook** [comment]
> For the first item, are you thinking of keeping the exact same struct, but make the fields private and provide public get_ and set_ methods for each field? If so that's also something I can do (in a separate PR probably).

Yes. Still, I'm not 100% sure that it's ergonomic for such a big structure, and also that it's justified, because the structure should almost never change (I mean a standard for resolv.conf doesn't change). So I'm open for other opinions.

**Comment by little-dude** [comment]
> I'm not 100% sure that it's ergonomic for such a big structure, and also that it's justified, because the structure should almost never change

I agree with you on this. If we decide not to change that, then the only thing that remains for 0.5 is the documentation and the code examples in `lib.rs`, which I try addressing in https://github.com/tailhook/resolv-conf/pull/4

**Comment by tailhook** [comment]
Let's keep it as is. This library is not fundamental as `failure` or `abstract-ns`. I believe it would be used in dependency chain once and not re-exported. So probably breaking changes to this library should not be painful.

So give me few nights to review API again, just to make sure everything is fine.

**Comment by tailhook** [comment]
Proposed changes:

1. `Ip` -> `ScopedIp`
2. `Ip::parse` -> `FromStr`

What do you think?

**Comment by little-dude** [comment]
1. Yeah. `ScopedIp` is definitely more specific.
2. 👍 as well.

**Comment by tailhook** [comment]
Okay. Done that. Cut a new release. Congrats!
