### ISSUE TITLE
`nameserver` if not set default to use name server on the local machine

### ISSUE THREAD

**Issue by cssivision** [tailhook/resolv-conf#7]
detail in http://man7.org/linux/man-pages/man5/resolv.conf.5.html

**Comment by tailhook** [comment]
Same reason, I've described [here](https://github.com/tailhook/resolv-conf/issues/9#issuecomment-348938827) and a same solution. We want resolv-conf crate to be a raw parser and may provide methods filling defaults.

**Comment by cssivision** [comment]
fixed by https://github.com/tailhook/resolv-conf/pull/10
