### ISSUE TITLE
`nameserver` limit max to 3

### ISSUE THREAD

**Issue by cssivision** [tailhook/resolv-conf#8]
defail in http://man7.org/linux/man-pages/man5/resolv.conf.5.html

**Comment by tailhook** [comment]
I think we have to parse all the name server directives. We may provide a method like `normalize()`  or even `glibc_normalize()` or `linux_normalize()` which truncates nameserver number to three and `search` domains six, and presumably also returns a list of warnings, so application can log them.

There are many historical precedents where such kind of limits were changed over time, and there are no technical reasons why these specific limits should be enforced.

Would you like to make a PR which normalization method(s)?
