### ISSUE TITLE
domain should hava a default value

### ISSUE THREAD

**Issue by cssivision** [tailhook/resolv-conf#9]
If no domain entry is present, the domain is determined from the local hostname returned by gethostname(2)

**Comment by tailhook** [comment]
Hi! Thank you for a review. Still I think this crate must be only parser of resolv.conf file. For example in OS X there are `/etc/resolve/*` files, which have the same format but `domain` option treated differently.

On the other hand we may make a method: `.get_domain_or_fallback()` to do that (the other thing it might have to do is look `LOCALDOMAIN` env variable). Would you like to make a PR? (but note #6)

**Comment by cssivision** [comment]
it seems https://github.com/tailhook/resolv-conf/pull/6 is a big change, i will fire a pr after that is merged.

**Comment by tailhook** [comment]
#6 is landed. This is a good time to discuss API for this issue so that we don't need to make a breaking release again.
